INSERT INTO PLAYGROUND (ID, NAME)
VALUES (1, 'Playground name 1');

INSERT INTO PLAY_SITE (ID, PLAYGROUND_ID, NAME, MAXIMUM_KID_VISITING_COUNT)
VALUES (1, 1, 'Play site name 1', 1);

INSERT INTO ATTRACTION (ID, PLAY_SITE_ID, SERIAL_NUMBER, TYPE)
VALUES (1, 1, 'SSR12L5', 'SLIDE');

INSERT INTO KID (ID, NAME, AGE, TICKET_NUMBER)
VALUES (1, 'Janar', 41, 'TIC336');

INSERT INTO KID_PLAY_SITE_VISIT (ID, KID_ID, PLAY_SITE_ID, STATUS, START_AT)
VALUES (1, 1, 1, 'PLAYING', NOW());