INSERT INTO PLAYGROUND (ID, NAME)
VALUES (1, 'Playground name 1');

INSERT INTO PLAY_SITE (ID, PLAYGROUND_ID, NAME, MAXIMUM_KID_CAPACITY)
VALUES (1, 1, 'Play site name 1', 10);

INSERT INTO ATTRACTION (ID, PLAY_SITE_ID, SERIAL_NUMBER, TYPE)
VALUES (1, 1, 'SSR12L5', 'SLIDE');